[package]
name = "ipv4-geolocate-webservice"
version = "0.1.0"
authors = ["Max Neuvians <max.neuvians@cds-snc.ca>"]

[dependencies]
hyper = "1.1"
maxminddb = "0.13"
pretty_env_logger = "0.3.1"
regex = "1.3.1"
serde_json = "1.0.41"