name: Build and deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
    - uses: actions/checkout@master
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Configure docker
      uses: actions/gcloud/cli@master
      with:
        args: auth configure-docker --quiet
    - name: Build the Docker image
      uses: docker://docker:stable
      with:
        entrypoint: sh
        args: -c "make build"
    - name: Push
      uses: docker://docker:stable
      with:
        entrypoint: sh
        args: -c "make push"