name: Build and deploy
on:
  schedule:
    - cron:  '0 12 * * 3'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
    - uses: actions/checkout@master
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Configure docker
      uses: actions/gcloud/cli@master
      with:
        args: auth configure-docker --quiet
    - name: Build the Docker image
      uses: actions/gcloud/cli@master
      with:
        entrypoint: sh
        args: -c "docker build -t gcr.io/cdssnc/ipv4-geolocate-webservice:latest -t gcr.io/cdssnc/ipv4-geolocate-webservice:`date '+%Y-%m-%d'` ."
    - name: Push
      uses: actions/gcloud/cli@master
      with:
        entrypoint: sh
        args: -c "docker push gcr.io/cdssnc/ipv4-geolocate-webservice:latest && docker push gcr.io/cdssnc/ipv4-geolocate-webservice:`date '+%Y-%m-%d'`"